# Author: Youzhi Luo (yzluo@tamu.edu)
# Updated by: Anmol Anand (aanand@tamu.edu)

BATCH_SIZE = 'batch_size'
INITIAL_LR = 'start_lr'
GENERATOR_STEPS = 'g_steps'
TEST_INTERVAL = 'test_interval'
LOSS_INTERVAL = 'loss_interval'
FACTOR = 'factor'
PATIENCE = 'patience'
MIN_LR = 'min_lr'
MAX_NUM_EPOCHS = 'max_num_epochs'
REWARD_GEN_STATE_PATH = 'dis_model_path'
BASELINE = 'baseline'
MOVING_RATIO = 'moving_ratio'
SAVE_MODEL = 'save_model'
GENERATOR_PARAMS = 'gen_param'

NUM_LAYERS = 'num_layers'
HID_DIM = 'hid_dim'
MAX_NUM_AUG = 'max_num_aug'
USE_STOP_AUG = 'use_stop_aug'
UNIFORM = 'uniform'
RNN_INPUT = 'rnn_input'
AUG_TYPE_PARAMS = 'aug_type_param_dict'

TEMPERATURE = 'temperature'
TRAINING = 'training'
MAGNITUDE = 'magnitude'
NODE_FEAT_DIM = 'node_feat_dim'

HIDDEN_UNITS = 'hidden'
MODEL_TYPE = 'model_type'
POOL_TYPE = 'pool_type'
FUSE_TYPE = 'fuse_type'
PRE_TRAIN_PATH = 'pre_train_path'
IN_DIMENSION = 'in_dim'
EDGE_IN_DIMENSION = 'edge_in_dim'
REWARD_GEN_PARAMS = 'dis_param'

MODEL_NAME = 'model_name'
DROPOUT = 'dropout'
AUG_MODEL_PATH = 'aug_model_path'
NUM_CLASSES = 'num_classes'
