NUM_LAYERS = 'num_layers'
HIDDEN_UNITS = 'hidden'
MODEL_TYPE = 'model_type'
POOL_TYPE = 'pool_type'
FUSE_TYPE = 'fuse_type'

BATCH_SIZE = 'batch_size'
INITIAL_LR = 'initial_lr'
FACTOR = 'factor'
PATIENCE = 'patience'
MIN_LR = 'min_lr'
MAX_NUM_EPOCHS = 'max_num_epochs'
PRE_TRAIN_PATH = 'pre_train_path'
IN_DIMENSION = 'in_dimension'

DISCRIMINATOR_PARAMS = 'discriminator_params'
